require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/stars", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Star. As you add validations to Star, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Star.create! valid_attributes
      get stars_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      star = Star.create! valid_attributes
      get star_url(star)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_star_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      star = Star.create! valid_attributes
      get edit_star_url(star)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Star" do
        expect {
          post stars_url, params: { star: valid_attributes }
        }.to change(Star, :count).by(1)
      end

      it "redirects to the created star" do
        post stars_url, params: { star: valid_attributes }
        expect(response).to redirect_to(star_url(Star.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Star" do
        expect {
          post stars_url, params: { star: invalid_attributes }
        }.to change(Star, :count).by(0)
      end

    
      it "renders a successful response (i.e. to display the 'new' template)" do
        post stars_url, params: { star: invalid_attributes }
        expect(response).to be_successful
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested star" do
        star = Star.create! valid_attributes
        patch star_url(star), params: { star: new_attributes }
        star.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the star" do
        star = Star.create! valid_attributes
        patch star_url(star), params: { star: new_attributes }
        star.reload
        expect(response).to redirect_to(star_url(star))
      end
    end

    context "with invalid parameters" do
    
      it "renders a successful response (i.e. to display the 'edit' template)" do
        star = Star.create! valid_attributes
        patch star_url(star), params: { star: invalid_attributes }
        expect(response).to be_successful
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested star" do
      star = Star.create! valid_attributes
      expect {
        delete star_url(star)
      }.to change(Star, :count).by(-1)
    end

    it "redirects to the stars list" do
      star = Star.create! valid_attributes
      delete star_url(star)
      expect(response).to redirect_to(stars_url)
    end
  end
end
